// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

var licenseNumber = 5;

if (licenseNumber !== undefined) {
  console.log("The person's license number is " + licenseNumber.toString());
} else {
  console.log("No license");
}

var personHasACar = true;

var x = 5;

var y = Caml_option.some(undefined);

exports.personHasACar = personHasACar;
exports.licenseNumber = licenseNumber;
exports.x = x;
exports.y = y;
/*  Not a pure module */
