// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myValue = {
  contents: 5
};

myValue.contents = 10;

var five = myValue.contents;

exports.myValue = myValue;
exports.five = five;
/*  Not a pure module */
