// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var a = "1";

console.log(a);

var hello = "hello";

var world = "world";

var message = hello + world;

var area = 200;

console.log("area:", area);

function add(a, b) {
  return a + b | 0;
}

var result = 1;

var result$1 = result + 1 | 0;

var A = {
  b: 4
};

var B = {
  b: 4
};

exports.a = a;
exports.hello = hello;
exports.world = world;
exports.message = message;
exports.area = area;
exports.add = add;
exports.result = result$1;
exports.A = A;
exports.B = B;
/*  Not a pure module */
