// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function greet(name) {
  return "Hello " + name;
}

function greetMore(name) {
  return "Hello " + name;
}

function addCoordinates(x, y) {
  return x + y | 0;
}

function drawCircle(color, radius, param) {
  if (radius !== undefined) {
    console.log(2);
  } else {
    console.log(1);
  }
}

function drawCircle1(radiusOpt, color, param) {
  console.log(1);
}

function callSecond(_param) {
  while(true) {
    _param = undefined;
    continue ;
  };
}

function callFirst(_param) {
  while(true) {
    _param = undefined;
    continue ;
  };
}

function add(x, y) {
  return x + y | 0;
}

var b = add(1, 2);

var a = 3;

exports.greet = greet;
exports.greetMore = greetMore;
exports.addCoordinates = addCoordinates;
exports.a = a;
exports.drawCircle = drawCircle;
exports.drawCircle1 = drawCircle1;
exports.callSecond = callSecond;
exports.callFirst = callFirst;
exports.add = add;
exports.b = b;
/* b Not a pure module */
