// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var areYouCrushingIt = /* No */1;

var singleData = /* Instagram */{
  _0: "hello"
};

var myAccount = {
  TAG: /* Facebook */1,
  _0: "Josh",
  _1: 26
};

var friendAccount = {
  TAG: /* Instagram */0,
  _0: "Jenny"
};

var me = {
  TAG: /* Id */1,
  _0: {
    name: "Joe",
    password: "123"
  }
};

exports.areYouCrushingIt = areYouCrushingIt;
exports.singleData = singleData;
exports.myAccount = myAccount;
exports.friendAccount = friendAccount;
exports.me = me;
/* No side effect */
