// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myArray = [
  "hello",
  "world",
  "how are you"
];

var pushedValue = myArray.push("bye");

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

exports.myArray = myArray;
exports.pushedValue = pushedValue;
exports.myList = myList;
/* pushedValue Not a pure module */
