// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function validateAge(param) {
  console.log(1);
}

function getAge(param) {
  console.log(1);
}

function parseData(a) {
  console.log(1);
}

console.log(1);

console.log(1);

console.log(1);

var b = 1;

exports.validateAge = validateAge;
exports.getAge = getAge;
exports.parseData = parseData;
exports.b = b;
/*  Not a pure module */
