// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newTu = [
  11,
  1
];

function getCenterCoordinates(param) {
  return [
          1,
          1.0
        ];
}

var tu = [
  1,
  1.0
];

var x = 1;

var y = 1.0;

exports.tu = tu;
exports.x = x;
exports.y = y;
exports.newTu = newTu;
exports.getCenterCoordinates = getCenterCoordinates;
/* No side effect */
