// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var p1 = new Promise((function (resolve, _reject) {
        resolve("hello world");
      }));

var p2 = Promise.resolve("some value");

exports.p1 = p1;
exports.p2 = p2;
/* p1 Not a pure module */
