// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var greeting = "Hello world!";

var name = greeting + " My name is Jack.";

var secondGreeting = "Hello " + name + "";

var r = /b/g;

var multilineGreeting = "Hello\n world!";

var firstLetterOfAlphabet = /* 'a' */97;

var b = true;

var f = false;

var i = 1;

var j = 1.0;

exports.greeting = greeting;
exports.multilineGreeting = multilineGreeting;
exports.name = name;
exports.secondGreeting = secondGreeting;
exports.firstLetterOfAlphabet = firstLetterOfAlphabet;
exports.r = r;
exports.b = b;
exports.f = f;
exports.i = i;
exports.j = j;
/* No side effect */
