// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


for(var x = 1; x <= 3; ++x){
  console.log(x);
}

var $$break = {
  contents: false
};

while(!$$break.contents) {
  if (Math.random() > 0.3) {
    $$break.contents = true;
  } else {
    console.log("Still running");
  }
};

var isMorning = true;

var message = "Good morning!";

exports.isMorning = isMorning;
exports.message = message;
exports.$$break = $$break;
/*  Not a pure module */
