// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

function add2(a, b) {
  return a + b | 0;
}

function add3(a, b) {
  return a + b | 0;
}

var gpa = 2.1 + 10;

var score = 10;

var scoreValue = 1;

var a = [
  10,
  20,
  20
];

var b = [
  10.5,
  20.5,
  20.5
];

var age = 10;

exports.score = score;
exports.add = add;
exports.add2 = add2;
exports.add3 = add3;
exports.scoreValue = scoreValue;
exports.a = a;
exports.b = b;
exports.age = age;
exports.gpa = gpa;
/* No side effect */
