// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function render(myColor) {
  if (myColor === "green" || myColor === "red") {
    console.log("Hello other colors");
  } else {
    console.log("Hello blue!");
  }
}

function render1(myColor) {
  if (myColor === "yellow") {
    console.log("Hello yellow!");
  } else if (myColor === "green") {
    console.log("Hello green!");
  } else {
    console.log("Hello blue!");
  }
}

console.log("This red-ish");

console.log("This is red-ish");

var message = "Hello Apple";

var me = {
  NAME: "Instagram",
  VAL: "Jenny"
};

var him = {
  NAME: "Facebook",
  VAL: [
    "Josh",
    26
  ]
};

var myColor = "Ruby";

var basic = "Red";

var foreground = "Green";

var background = "Red";

var theCompany = "Apple";

exports.render = render;
exports.render1 = render1;
exports.me = me;
exports.him = him;
exports.myColor = myColor;
exports.basic = basic;
exports.foreground = foreground;
exports.background = background;
exports.theCompany = theCompany;
exports.message = message;
/*  Not a pure module */
