// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

var me = {
  age: 5,
  name: "Big ReScript"
};

var name = me.name;

var newrecord = Caml_obj.obj_dup(me);

newrecord.age = me.age + 1 | 0;

me.age = 18;

var newrecord$1 = Caml_obj.obj_dup(me);

newrecord$1.name = undefined;

var someName = "Big ReScript";

var newrecord$2 = Caml_obj.obj_dup(me);

newrecord$2.name = someName;

var match = me.name;

var isRescript = match === "ReScript" ? true : false;

var nameWasSet = me.name !== undefined;

var meNextYear = newrecord;

var withoutName = newrecord$1;

var optionName = newrecord$2;

exports.me = me;
exports.name = name;
exports.meNextYear = meNextYear;
exports.withoutName = withoutName;
exports.someName = someName;
exports.optionName = optionName;
exports.isRescript = isRescript;
exports.nameWasSet = nameWasSet;
/*  Not a pure module */
